services:
  ros_dev:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/learn-ros:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      DISPLAY: novnc:0.0
    depends_on:
      - novnc
    network_mode: service:novnc
  # https://wiki.ros.org/docker/Tutorials/GUI#Using_noVNC
  novnc:
    image: theasp/novnc:latest
    ports:
      - '8080:8080'
    environment:
      DISPLAY_WIDTH: '3000'
      DISPLAY_HEIGT: '1800'
      RUN_XTERM: no
