version: '3.8'
services:
  ros_dev:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    ports:
      - '6080:80'
    volumes:
      - .:/workspaces/learn-ros:cached
    # environment:
    security_opt:
      - seccomp=unconfined
    shm_size: '512m'
