services:
  ros-dev:
    build:
      context: .
    volumes:
      - .:/workspaces/learn-ros:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ['sleep', 'infinity']
    # network_mode: host
    environment:
      DISPLAY: host.docker.internal:0
    # security_opt:
    #   - seccomp:unconfined
    # ipc: host
