FROM osrf/ros:jazzy-desktop-full

# RUN apt-get update && \
#     apt-get install -y \
#     xserver-xorg \
#     x11-apps \
#     && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces/learn-ros

RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc
